services:
  app:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
    depends_on:
      db:
        condition: service_healthy

  prisma:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: ["npx", "prisma", "studio"]
    ports:
      - '5555:5555'
    environment:
      NODE_ENV: development
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy
